monitors:
  eDP-1:
    position: "top"
    height: 30
    anchor_to_edges: true
    icon_theme: Paper
    start:
      - all_monitors: false
        type: workspaces
    center:
      - bar:
          - type: box
            class: container
            widgets:
              - label: "{{poll:3600000:weather '%TC - %I %D' -q 'London'}}"
                type: label
        class: 'weather'
        type: custom
      - type: clock
        format: '%A %d.%m.%Y %H:%M:%S'
    end:
      - format:
        - ' {cpu_percent}%'
        - ' {memory_used} / {memory_total} GB ({memory_percent}%)'
        - ' {swap_used} / {swap_total} GB ({swap_percent}%)'
        - ' {disk_used:/} / {disk_total:/} GB ({disk_percent:/}%)'
        - ' {disk_used:/home} / {disk_total:/home} GB ({disk_percent:/home}%)'
        - ' {net_down:enp3s0} / {net_up:enp3s0} Mbps'
        - ' {uptime}'
        interval:
          cpu: 1
          disks: 300
          memory: 30
          networks: 3
          temps: 5
        type: sys_info